"""add

Revision ID: 9c2183ae85a1
Revises: 
Create Date: 2022-04-24 14:19:05.024102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2183ae85a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('keywords', sa.String(length=100), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('total_clicks_by_user', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('cate', sa.Enum('pure', 'wechat', 'phone'), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('job', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('wechat_id', sa.String(length=64), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('reg_time', sa.DateTime(), nullable=True),
    sa.Column('total_read_time', sa.BigInteger(), nullable=True),
    sa.Column('total_clicks', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('we_user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.Enum('1', '2'), nullable=True),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('head_img_url', sa.String(length=100), nullable=True),
    sa.Column('privilege', sa.String(length=100), nullable=True),
    sa.Column('union_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('we_user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('refresh_token', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_index(op.f('ix_we_user_token_access_token'), 'we_user_token', ['access_token'], unique=False)
    op.create_index(op.f('ix_we_user_token_code'), 'we_user_token', ['code'], unique=False)
    op.create_index(op.f('ix_we_user_token_refresh_token'), 'we_user_token', ['refresh_token'], unique=False)
    op.create_table('user2_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DATE(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('read_time', sa.Integer(), nullable=True),
    sa.Column('read_process', sa.String(length=5), nullable=True),
    sa.Column('is_like', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user2_news')
    op.drop_index(op.f('ix_we_user_token_refresh_token'), table_name='we_user_token')
    op.drop_index(op.f('ix_we_user_token_code'), table_name='we_user_token')
    op.drop_index(op.f('ix_we_user_token_access_token'), table_name='we_user_token')
    op.drop_table('we_user_token')
    op.drop_table('we_user_info')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('admin')
    # ### end Alembic commands ###
