"""add news frame

Revision ID: f374a6d9b2de
Revises: 9c2183ae85a1
Create Date: 2022-04-27 21:54:47.374304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f374a6d9b2de'
down_revision = '9c2183ae85a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('news', sa.Column('digest', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('cate', sa.String(length=5), nullable=False))
    op.add_column('news', sa.Column('hpic', sa.String(length=64), nullable=True))
    op.add_column('news', sa.Column('heat', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'heat')
    op.drop_column('news', 'hpic')
    op.drop_column('news', 'cate')
    op.drop_column('news', 'digest')
    op.drop_column('news', 'title')
    # ### end Alembic commands ###
